### ISSUE TITLE
Getting double red astrick "*" for "required" field.  

### ISSUE THREAD

**Issue by drMikeinTampa** [BrilliantPlugins/salesforce-wordpress-to-lead#85]
For some reason on my website when I changed the contact form to require a phone number there are 2 red astricks.  I don't mind one, but two looks odd.  Does anyone know how to fix?  Example page: https://www.summerlandcamps.com/contact-form/

**Comment by nick-hunter** [comment]
Not sure if you already figured this out, but the second one is coming from your theme. See if you can override it using your custom stylesheet. If you directly change the theme it could get overwritten when you update it.

```css
label.required:after {
	content:'*';
	display:inline-block;
	vertical-align:text-top;
	font-size:80%;
	color:#da6f5b;
}
```
